name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service cozy-wisdom

  notificar-success:
  if: success() 
  needs: [deploy]
  runs-on: ubuntu-latest
  steps:
    - name: Enviar notificación a Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: "GitHub Actions"
        SLACK_TITLE: "CI/CD exitoso"
        SLACK_MESSAGE: |
          El pipeline de CI/CD se ejecutó correctamente para:
          • Repo: ${{ github.repository }}
          • Commit: ${{ github.event.head_commit.message }}
          • Autor: ${{ github.event.head_commit.author.name }}
          Ver workflow: ${{ github.server_url }}/${{ github.repository }}/actions
        SLACK_COLOR: good

  notificar-failure:
    if: failure() 
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "GitHub Actions"
          SLACK_TITLE: "CI/CD fallido"
          SLACK_MESSAGE: |
            El pipeline de CI/CD se ejecutó incorrectamente para:
            • Repo: ${{ github.repository }}
            • Commit: ${{ github.event.head_commit.message }}
            • Autor: ${{ github.event.head_commit.author.name }}
            Ver workflow: ${{ github.server_url }}/${{ github.repository }}/actions
          SLACK_COLOR: danger